let x; // X position of the ellipse
let y; // Y position of the ellipse, generated by Perlin noise
let t; // Perlin noise time increment, smaller is smoother

function setup() {
  createCanvas(windowWidth, windowHeight);
  background(24);
  noStroke();
  smooth();

  x = 0; // Starting on the left hand side
  t = random(10000);
  y = noise(t);
}

function draw() {
  y = map(noise(t), 0, 1, 0, height);
  t+=0.001;

  ellipse(x, y, 4, 1);
  x+=2;

  if (x >= width) {
    background(24);
    x = 0;
  }
}
